### ISSUE TITLE
pod has unbound immediate PersistentVolumeClaims (repeated 3 times)

### ISSUE THREAD

**Issue by purgeyao** [paderlol/nacos-k8s#1]
果然 启动nacos错误了

**Comment by purgeyao** [comment]
nfs-client-provisioner日志
`E0605 03:43:25.712382       1 leaderelection.go:234] error retrieving resource lock nacos/fuseim.pri-ifs: endpoints "fuseim.pri-ifs" is forbidden: User "system:serviceaccount:nacos:nfs-client-provisioner" cannot get resource "endpoints" in API group "" in the namespace "nacos"`

**Comment by NominationP** [comment]
怎么解决的

**Comment by NominationP** [comment]
怎么解决的

**Comment by purgeyao** [comment]
nacos 建议部署在 实体机器， 目前公司测试下来  大量服务 在k8s 调用会存在网络问题

**Comment by paderlol** [comment]
对，grpc似乎有点问题

**Comment by purgeyao** [comment]
19年我们大量服务nacos在k8s部署 发现一些dns 不稳定问题，  还有同样的机器nacos 部署到k8s  和二进制部署  存在一定性能损耗，建议按照服务量 弄几台虚机部署nacos集群
